Repository xwp/stream, pull requests merged in 2024-08, with the labels that each got.

#1529 Adds Playwright, first tests and linting.
  .distignore
  .eslintrc.json
  .eslintrc.playwright.json
  .gitignore
  .vscode/extensions.json
  local/public/wp-content/plugins/hello.php
  package-lock.json
  package.json
  playwright.config.js
  tests/bootstrap.php
  tests/e2e/editor-new-post.spec.js
  tests/phpunit/alerts/test-class-alert-trigger-action.php
  tests/phpunit/alerts/test-class-alert-trigger-author.php
  tests/phpunit/alerts/test-class-alert-trigger-context.php
  tests/phpunit/connectors/test-class-connector-acf.php
  tests/phpunit/connectors/test-class-connector-blogs.php
  tests/phpunit/connectors/test-class-connector-comments.php
  tests/phpunit/connectors/test-class-connector-edd.php
  tests/phpunit/connectors/test-class-connector-editor.php
  tests/phpunit/connectors/test-class-connector-installer.php
  tests/phpunit/connectors/test-class-connector-jetpack.php
  tests/phpunit/connectors/test-class-connector-media.php
  tests/phpunit/connectors/test-class-connector-menus.php
  tests/phpunit/connectors/test-class-connector-mercator.php
  tests/phpunit/connectors/test-class-connector-posts.php
  tests/phpunit/connectors/test-class-connector-settings.php
  tests/phpunit/connectors/test-class-connector-taxonomies.php
  tests/phpunit/connectors/test-class-connector-user-switching.php
  tests/phpunit/connectors/test-class-connector-users.php
  tests/phpunit/connectors/test-class-connector-wordpress-seo.php
  tests/phpunit/test-class-admin.php
  tests/phpunit/test-class-alert-trigger.php
  tests/phpunit/test-class-alert.php
  tests/phpunit/test-class-alerts-list.php
  tests/phpunit/test-class-alerts.php
  tests/phpunit/test-class-author.php
  tests/phpunit/test-class-connector.php
  tests/phpunit/test-class-connectors.php
  tests/phpunit/test-class-date-interval.php
  tests/phpunit/test-class-db-driver-wpdb.php
  tests/phpunit/test-class-db.php
  tests/phpunit/test-class-export.php
  tests/phpunit/test-class-exporter-csv.php
  tests/phpunit/test-class-exporter-json.php
  tests/phpunit/test-class-filter-input.php
  tests/phpunit/test-class-log.php
  tests/phpunit/test-class-plugin.php
  tests/phpunit/test-functions.php
Labels: tooling

#1542 Display feature request notice on Settings screen
  classes/class-admin.php
  ui/css/admin.css
Labels: enhancement

#1538 add files to generate and remove test data
  contributing.md
  docker-compose.yml
  local/scripts/large-datasets/bulk-insert-logs.sample.sql
  local/scripts/large-datasets/bulk-insert-logs.sql
  local/scripts/large-datasets/generate-bulk-insert.php
  local/scripts/large-datasets/remove-test-logs.sql
  local/scripts/large-datasets/show-stream-db-stats.sql
  package.json
Labels: tooling

#1543 Use scheduled action for resetting large record and meta tables
  classes/class-admin.php
  classes/class-plugin.php
  classes/class-settings.php
  composer.json
  composer.lock
  contributing.md
  package.json
  tests/phpunit/test-class-admin.php
Labels: bug

#1547 Fix local environment path
  .gitignore
  classes/class-plugin.php
  playwright.config.js
  tests/e2e/editor-new-post.spec.js
  tests/e2e/network-activated.spec.js
  tests/e2e/setup/setup.js
Labels: bug
