Repository xwp/stream, pull requests merged in 2024-07, with the labels that each got.

#1505 publish docker image on master only again
  .github/workflows/docker-images.yml
Labels: needs discussion

#1507 Update `wp-coding-standards/wpcs` and fix lint issues
  alerts/class-alert-trigger-action.php
  alerts/class-alert-trigger-context.php
  alerts/class-alert-type-email.php
  alerts/class-alert-type-highlight.php
  alerts/class-alert-type-ifttt.php
  alerts/class-alert-type-menu-alert.php
  alerts/class-alert-type-slack.php
  classes/class-admin.php
  classes/class-alert-trigger.php
  classes/class-alert.php
  classes/class-alerts-list.php
  classes/class-alerts.php
  classes/class-author.php
  classes/class-cli.php
  classes/class-connector.php
  classes/class-db.php
  classes/class-export.php
  classes/class-filter-input.php
  classes/class-form-generator.php
  classes/class-list-table.php
  classes/class-log.php
  classes/class-plugin.php
  classes/class-settings.php
  composer.json
  composer.lock
  connectors/class-connector-acf.php
  connectors/class-connector-buddypress.php
  connectors/class-connector-comments.php
  connectors/class-connector-edd.php
  connectors/class-connector-gravityforms.php
  connectors/class-connector-jetpack.php
  connectors/class-connector-menus.php
  connectors/class-connector-mercator.php
  connectors/class-connector-posts.php
  connectors/class-connector-settings.php
  connectors/class-connector-user-switching.php
  connectors/class-connector-widgets.php
  connectors/class-connector-woocommerce.php
  connectors/class-connector-wordpress-seo.php
  includes/feeds/atom.php
  includes/feeds/json.php
  includes/feeds/rss-2.0.php
  includes/functions.php
  package.json
Labels: compatibility, tooling

#1509 Enable `phpcs` sniffs for PHPUnit test files
  composer.json
  package.json
  tests/bootstrap.php
  tests/phpcs.xml.dist
  tests/testcase.php
  tests/tests/alerts/test-class-alert-trigger-action.php
  tests/tests/alerts/test-class-alert-trigger-author.php
  tests/tests/alerts/test-class-alert-trigger-context.php
  tests/tests/connectors/test-class-connector-acf.php
  tests/tests/connectors/test-class-connector-blogs.php
  tests/tests/connectors/test-class-connector-comments.php
  tests/tests/connectors/test-class-connector-edd.php
  tests/tests/connectors/test-class-connector-editor.php
  tests/tests/connectors/test-class-connector-installer.php
  tests/tests/connectors/test-class-connector-jetpack.php
  tests/tests/connectors/test-class-connector-media.php
  tests/tests/connectors/test-class-connector-menus.php
  tests/tests/connectors/test-class-connector-mercator.php
  tests/tests/connectors/test-class-connector-posts.php
  tests/tests/connectors/test-class-connector-settings.php
  tests/tests/connectors/test-class-connector-taxonomies.php
  tests/tests/connectors/test-class-connector-user-switching.php
  tests/tests/connectors/test-class-connector-users.php
  tests/tests/test-class-admin.php
  tests/tests/test-class-alert-trigger.php
  tests/tests/test-class-alert.php
  tests/tests/test-class-alerts-list.php
  tests/tests/test-class-alerts.php
  tests/tests/test-class-author.php
  tests/tests/test-class-connector.php
  tests/tests/test-class-connectors.php
  tests/tests/test-class-db-driver-wpdb.php
  tests/tests/test-class-db.php
  tests/tests/test-class-export.php
  tests/tests/test-class-exporter-csv.php
  tests/tests/test-class-filter-input.php
  tests/tests/test-class-log.php
  tests/tests/test-class-plugin.php
  tests/tests/test-functions.php
Labels: enhancement, tooling

#1508 Fix Uncaught ValueError in Gravity Forms and WordPress SEO connectors
  .gitignore
  classes/class-connector.php
  composer.json
  composer.lock
  connectors/class-connector-gravityforms.php
  connectors/class-connector-wordpress-seo.php
  local/public/wp-config.php
  package.json
  phpunit.xml
  tests/bootstrap.php
  tests/testcase.php
  tests/tests/connectors/test-class-connector-wordpress-seo.php
  tests/tests/test-class-connector.php
Labels: bug

#1512 Require PHP ≥ 7.0 and WordPress ≥ 4.6
  composer.json
  composer.lock
  phpcs.xml.dist
  readme.txt
  stream.php
Labels: enhancement, compatibility

#1494 Fix more PHP 8.1 compatibility issues
  alerts/class-alert-type-email.php
  alerts/class-alert-type-ifttt.php
  classes/class-alert.php
  classes/class-alerts.php
  classes/class-date-interval.php
  composer.json
  composer.lock
  connectors/class-connector-acf.php
  connectors/class-connector-jetpack.php
  includes/lib/Carbon.php
  local/public/wp-config.php
  tests/tests/test-class-date-interval.php
Labels: compatibility

#1513 Replace `strlen` with custom callback that accepts `null`
  classes/class-log.php
Labels: compatibility

#1517 BuddyPress Connector: Check for BP dependencies before blindly assuming they're available
  connectors/class-connector-buddypress.php
Labels: bug

#1518 Document Connectors
  connectors.md
  contributing.md
  local/scripts/generate-connector-docs.php
  package.json
  readme.md
Labels: documentation

#1522 fix offset warning in Slack alert when there is no custom logo
  alerts/class-alert-type-slack.php
  local/public/.gitignore
Labels: bug

#1521 Use GitHub action for doing WP.org deployment
  .distignore
  .github/workflows/deploy-to-wp-org.yml
  .github/workflows/docker-images.yml
  .nvmrc
  .wordpress-org/banner-1544x500.png
  .wordpress-org/banner-772x250.png
  .wordpress-org/banner.svg
  .wordpress-org/icon-128x128.png
  .wordpress-org/icon-256x256.png
  .wordpress-org/icon.svg
  .wordpress-org/screenshot-1.png
  .wordpress-org/screenshot-2.png
  .wordpress-org/screenshot-3.png
  Gruntfile.js
  contributing.md
  package-lock.json
  package.json
Labels: enhancement, tooling, work in progress

#1534 Include timezone in logs for clarity
  classes/class-export.php
  classes/class-list-table.php
  ui/css/admin.css
Labels: bug, enhancement

#1532 Add object ID and user ID to exports
  classes/class-export.php
  tests/tests/test-class-export.php
Labels: enhancement

#1531 Allow commas in CSV exporter fields
  exporters/class-exporter-csv.php
  tests/tests/test-class-export.php
Labels: bug

#1533 add port so we can see the database
  contributing.md
  docker-compose.yml
Labels: tooling

#1530 Remove duplicate logs when saving posts
  composer.json
  composer.lock
  connectors/class-connector-posts.php
Labels: bug
